version: "3"
services:
  db:
    build:
      context: .
      dockerfile: loglist-db.dockerfile
    environment:
      - POSTGRES_USER=horta
      - POSTGRES_PASSWORD=hell
      - POSTGRES_DB=loglist
  loglist:
    depends_on:
      - db
    build:
      context: .
      dockerfile: loglist.dockerfile
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=jdbc:postgresql://db/loglist?user=horta&password=hell
      - APPLY_EVOLUTIONS_SILENTLY=true

      # Any *valid* pair of keys will work for localhost. You can generate one here: https://www.google.com/recaptcha/admin
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY

      - BASIC_AUTH_USERNAME=horta
      - BASIC_AUTH_PASSWORD=hell

      - APPROVAL_SMTP_HOST="smtp.example.com"
      - APPROVAL_EMAIL="noreply@example.com"
      - APPROVAL_EMAIL_PASSWORD="hortahell"
