name: Docker
on:
  push:
    tags:
      - '*'

jobs:
  push:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./loglist.dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: codingteam/loglist
          tag_with_ref: true
          tags: latest
