name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [ ubuntu-20.04, windows-2019 ]
    steps:
      - uses: actions/checkout@v2
      - name: SBT Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}.sbt.${{ hashFiles('**/*.sbt') }}+${{ hashFiles('project/build.properties') }}

      - name: Build
        run: sbt dist
